### ISSUE TITLE
nvim config

### ISSUE THREAD

**Issue by AhmadFudl** [mTvare6/gruvbox-wallpaper#2]
I came here from simple-bar main page.
sorry couldn't find a proper way to contact you.
So making it short like what the title says I'm here asking for that neovim config??
it looks cool

**Comment by mTvare6** [comment]
My config has now changed a lot, do you still want it?
![image](https://user-images.githubusercontent.com/57838468/136018613-2106e12f-ee74-4d8f-b934-b8f8ec2a879c.png)

**Comment by AhmadFudl** [comment]
yeah i would be happy to see it thanks
